baseURL = "https://colinbledsoe.netlify.app/"
testURL = "http://localhost:1313"
languageCode = "en-us"
title = "ColinBledsoe"
theme = "hugo-geekblog"

# Google Analytics
googleAnalytics = "G-92GNDHM20N"

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

# summaryLength = 35 shorten the summary from default 70 words

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
    
[taxonomies]
  author = "authors"
  tag = "tags"
  series = "series"

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.Atom]
    # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
    name = "Atom"
    mediaType = "application/atom+xml"
    # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
    baseName = "atom"
    isPlainText = false
    rel = "alternate"
    isHTML = false
    noUgly = true
    permalinkable = false

  [outputs]
  home = ["HTML", "ATOM"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML", "ATOM"]

[params]
  subtitle = "Chemical Engineering and Data Science"
  description = "This is my personal blog."
  keywords = []
  images = []

  # (Optional, default static/brand.svg) Set the path to a logo for the Geekblog
  # relative to your 'static/' folder.
  #logo = "logo.png"

  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter.
  geekblogToC = 6

  # (Optional, default none) Add a link to your Legal Notice page to the site footer.
  # It can be either a remote url or a local file path relative to your content directory.
  #geekblogLegalNotice = "https://blog.example.com/legal"

  # (Optional, default none) Add a link to your Privacy Policy page to the site footer.
  # It can be either a remote url or a local file path relative to your content directory.
  #geekblogPrivacyPolicy = "/privacy"

  # (Optional, default true) Add an anchor link to headlines.
  #geekblogAnchor = true

  # (Optional, default true) Copy anchor url to clipboard on click.
  #geekblogAnchorCopy = true

  # (Optional, default none) Sites main author.
  geekblogAuthor = "colinbledsoe"

  # (Optional, default none) Adds a "Hosted on <provider>" line to the footer.
  # Could be used if you want to give credits to your hosting provider.
  #[params.geekblogHostedOn]
  #  name = "Uberspace"
  #  link = "https://uberspace.de/en/"

  # (Optional, default none) Adds a "Content licensed under <license>" line to the footer.
  # Could be used if you want to define a default license for your content.
  #[params.geekblogContentLicense]
  #  name = "CC BY-SA 4.0"
  #  link = "https://creativecommons.org/licenses/by-sa/4.0/"

  